### ISSUE TITLE
Grid does not appear if inside ScrollView

### ISSUE THREAD

**Issue by uzumakinaruto123** [ceryle/FitGridView#3]
If I use FitGridView inside ScrollView, Grid does not appear. Even if FitGridView is a nested child. 

Also, is there any way to specify minimum grid dimensions like height. Because I am using same Grid Adapter in two places. In one activity, Grid is the only element so it takes full height of the screen accordingly. 

Second grid is in the fragment where I expect it to take same dimensions as in previous activity. But, here it tries to fit in available height making images inside grid smaller. I want to keep same dimensions of Cell as in previous activity and want to let it scroll.

Thanks!

**Comment by ceryle** [comment]
Hi,
I will look at this issue, soon.

**Comment by ceryle** [comment]
Hi,
You can use FitGridView inside ScrollView, it will be visible if you set height in units and put it in any layout. However, if you give MATCH_PARENT to FitGridViews's height attribute, it will not be visible because of heightMeasureSpec 0 issue. For the second part of your question, in FitGridView recycling of views is not enabled. So, you should not use it if you want scrolling, instead try to use RecyclerView with its GridLayoutManager.
Good luck!

**Comment by uzumakinaruto123** [comment]
Ok, Thanks! I am trying FitGridView with scrolling too because the grid will have limited number of static elements. Can be closed 👍
